git:
  depth: false
language: java
jdk: oraclejdk11
env:
  global:
    - GH_PAGES_NAME='ga4gh-bot'
    - GH_PAGES_EMAIL='ga4ghdev@gmail.com'
    - secure: imUHv+9gdjqTQZbz/Cl9ZLxa/NQFowvUPyiyPvXAlu4Nw9jyuVhrFRHyZJXdACt6tnR6N6ig8zOE+0rymklySH2Z+zGOL1ZBHkWa0JYgYmq60+ARExqUXBlYneir/B91BGuF5en3DstD3uWPoHNON9WM+qbBLlpPvzh38XPfuWvK5qaYmsRfg4FxAeYzAItYSEmYkUDnzv5yTfZ1gc/B6lNkgFmJL/BcRAzzOAzgDEWHx7Y/DpXDPWeQPbxSsSE1h4K8HdZJCohhATRxMTDOkMdjmb8QNmNt5NyhTJ3QTjrF3Ecen0zQ37+xu8MB1gOQTEoq+FuLxM+1iKC7MMHntqJ/ZFD4ZzyPxdBG7u+nDUInoxSzeIrGGeJiehjwjN/bZ6ZhA4lD5GYrENO7JQ7Xlq2eFghiS8yHhphvvVKPGayiKLNaDHbJmNnuHDn6LVJHjW0ekGFYbI/PgD5x37LBHVEDa6qOkRbYFpT3Uvhy0Y6VR+hHCP8SPbR1HARnyX0O/nsjOZl6UAgyjPFLZGEXquGdJVggR/wNI1KfxJ5QfEHhTbx8+6ar40NuVbhSkSm5CN/xhUADpB2UGYRBNQgu5zOjHZAgqNCOcTsVQrzqW7B5mt3kVWVnDT+Mp+U7KbNpngf5UxbxowdCpphHZ1sWuYPpdA5g0EE+1ADY0usuBHU=
services: postgresql
before_script:
    - psql -c "create database test_db;" -U postgres
    - psql -c "create user test_user with password 'password';" -U postgres
    - psql -c "alter database test_db owner to test_user;" -U postgres
    - psql -c "alter user test_user with superuser;" -U postgres
    - psql test_db < ./config/test/db.test.bak -U test_user
script: "./gradlew test"
after_success:
    - "./gradlew jacocoTestReport"
    - bash <(curl -s https://codecov.io/bash)
    - chmod 755 ./config/ci/run-gh-openapi-docs.sh
    - "./config/ci/run-gh-openapi-docs.sh"
