/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package e2e.org.ga4gh.registry;

import org.ga4gh.registry.App;
import org.ga4gh.registry.AppConfig;
// import org.testng.annotations.*;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.web.WebAppConfiguration;
// import org.springframework.test.web.servlet.MockMvc;
// import org.springframework.test.web.servlet.setup.MockMvcBuilders;
// import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
// import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
// import org.ga4gh.registry.controller.ServiceInfo;
// import org.ga4gh.registry.controller.Services;

@SpringBootTest(classes = App.class)
@WebAppConfiguration
@ContextConfiguration(classes = {AppConfig.class})
public class AppTest {

    /*
    private MockMvc mockMvc;
    private MockMvc mockMvc2;

    @BeforeClass
    public void setup() {
        mockMvc = MockMvcBuilders.standaloneSetup(ServiceInfo.class).build();
        mockMvc2 = MockMvcBuilders.standaloneSetup(Services.class).build();
    }

    @Test
    public void helloGradle() throws Exception {
        System.out.println("Testing service-info");
        mockMvc.perform(get("/service-info"))
               .andExpect(status().isOk());
        System.out.println("Testing services");
        mockMvc2.perform(get("/services"))
               .andExpect(status().isOk());

        String results = new ServiceInfo().getServiceInfo();
        System.out.println("My service info results: ");
        System.out.println(results);
    }
    */
}
