/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ga4gh.registry;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Configuration;

@SpringBootApplication
@Configuration
public class App {
    
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    /*
    @Bean
    public Jackson2ObjectMapperBuilder configureObjectMapper() {
        Jackson2ObjectMapperBuilder builder =  new Jackson2ObjectMapperBuilder();
        builder.modulesToInstall(Hibernate4Module.class);
        builder.serializationInclusion(JsonInclude.Include.NON_NULL);
        return builder;
    }
    */
}
