/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ga4gh.registry;

import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.web.WebAppConfiguration;

@SpringBootTest(classes = App.class)
@WebAppConfiguration
@ContextConfiguration(classes = {AppConfig.class})
public class AppTest {
    
}
